suorganizer/blog/urls.py
from django.conf.urls import url

from blog.views import PostList, post_detail


urlpatterns = [
    url(r'^$', PostList.as_view(template_name = 'blog/post_list.html'), name='blog_post_list'),
    url(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/'
        r'(?P<slug>[\w\-]+)/$',
        post_detail, {'parent_template':'base.html'}, name='blog_post_detail'),
]

suorganizer/organizer/urls.py
from django.conf.urls import url

from organizer.views import startup_list, startup_detail, tag_list, tag_detail

urlpatterns = [
    url(r'^tag/$', tag_list, name='organizer_tag_list'),
    url(r'^tag/(?P<slug>[\w\-]+)/$', tag_detail, name='organizer_tag_detail'),
    url(r'^startup/$', startup_list, name='organizer_startup_list'),
    url(r'^startup/(?P<slug>[\w\-]+)/$', startup_detail, name='organizer_startup_detail'),
]

suorganizer/suorganizer/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from organizer import urls as organizer_urls
from blog import urls as blog_urls
from .views import redirect_root

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(organizer_urls)),
    url(r'^blog/', include(blog_urls)),
    url(r'^$', redirect_root),
]

suorganizer/blog/models.py
from django.db import models
from django.core.urlresolvers import reverse

from organizer.models import Startup, Tag

class Post(models.Model):
    title = models.CharField(max_length=63)
    slug = models.SlugField(max_length=63, help_text='A label for URL config', unique_for_month='pub_date')
    text = models.TextField()
    pub_date = models.DateField('date published', auto_now_add= True)
    tags = models.ManyToManyField(Tag, related_name='blog_posts')
    startups = models.ManyToManyField(Startup, related_name='blog_posts')

    def __str__(self):
        return "{} on {}".format(self.title, self.pub_date.strftime('%Y-%m-%d'))

    def get_absolute_url(self):
        return reverse('blog_post_detail', kwargs={'year': self.pub_date.year, 'month': self.pub_date.month ,'slug': self.slug})

    class Meta:
        verbose_name = 'blog post'
        ordering = ['-pub_date', 'title']
        get_latest_by = 'pub_date'

suorganizer/organizer/models.py
from django.db import models
from django.core.urlresolvers import reverse

class Tag(models.Model):
    name = models.CharField(max_length=31, unique=True)
    slug = models.SlugField(max_length=31, unique=True, help_text='A label for URL config')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('organizer_tag_detail', kwargs={'slug': self.slug})

    class Meta:
        ordering = ['name']


class Startup(models.Model):
    name = models.CharField(max_length=31, db_index=True)
    slug = models.SlugField(max_length=31, unique=True, help_text='A label for URL config')
    description = models.TextField()
    founded_date = models.DateField('date founded')
    contact = models.EmailField()
    website = models.URLField(max_length=255)
    tags = models.ManyToManyField(Tag)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('organizer_startup_detail', kwargs={'slug': self.slug})

    class Meta:
        ordering = ['name']
        get_latest_by = 'founded_date'

class NewsLink(models.Model):
    title = models.CharField(max_length=63)
    pub_date = models.DateField('date published')
    link = models.URLField(max_length=255)
    startup = models.ForeignKey(Startup)

    def __str__(self):
        return "{}:{}".format(self.startup,self.title)
        #we want startup object and the title
        #we could write self.startup.name which is same as self.startup beacuse of Startup.__str__()

    class Meta:
        verbose_name = 'news article'
        ordering = ['-pub_date']
        get_latest_by = 'pub_date'

suorganizer/blog/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'

    def clean_slug(self):
        return self.cleaned_data['slug'].lower()

suorganizer/organizer/forms.py
from django import forms
from .models import Tag, NewsLink, Startup
from django.core.exceptions import ValidationError

class SlugCleanMixin:
    def clean_slug(self):
        new_slug = (self.cleaned_data['slug'].lower())
        if new_slug == 'create':
            raise ValidationError('Slug may not be "create".')
        return new_slug

class TagForm(SlugCleanMixin, forms.ModelForm):
    class Meta:
        model = Tag
        fields = '__all__'

    def clean_name(self):
        return self.cleaned_data['name'].lower()

class NewsLinkForm(forms.ModelForm):
    class Meta:
        model = NewsLink
        fields = '__all__'

class StartUpForm(SlugCleanMixin, forms.ModelForm):
    class Meta:
        model = Startup
        fields = '__all__'

suorganizer/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import View

from .models import Post

class PostList(View):
    template_name = 'blog/post_list.html'
    def get(self, request):
        post_list = Post.objects.all()
        return render(request, self.template_name, {'post_list': post_list})

def post_detail(request, year, month, slug, parent_template = None):
    post = get_object_or_404(Post, pub_date__year = year, pub_date__month = month , slug__iexact = slug)
    return render(request, 'blog/post_detail.html', {'post': post, 'parent_template': parent_template})

suorganizer/organizer/views.py
from django.http.response import Http404, HttpResponse
from django.shortcuts import render_to_response, get_object_or_404, render
from django.template import loader

from .models import Tag, Startup

def tag_list(request):
    tag_list = Tag.objects.all()
    return render(request, 'organizer/tag_list.html', {'tag_list': tag_list})

def tag_detail(request, slug):
    tag = get_object_or_404(Tag, slug__iexact = slug)
    return render(request,'organizer/tag_detail.html', {'tag': tag})

def startup_list(request):
    startup_list = Startup.objects.all()
    return render(request,'organizer/startup_list.html',{'startup_list': startup_list})

def startup_detail(request, slug):
    startup = get_object_or_404(Startup, slug__iexact = slug)
    return render(request, 'organizer/startup_detail.html', {'startup': startup})

suorganizer/suorganizer/views.py
from django.shortcuts import redirect

def redirect_root(request):
    return redirect('blog_post_list')

suorganizer/blog/templates/blog/base_blog.html
{% extends parent_template|default:"base.html" %}

suorganizer/blog/templates/blog/post_confirm_delete.html
{% extends parent_template|default:"blog/base_blog.html" %}

{% block title %}
    {{ block.super }} - Delete Post
{% endblock %}

{% block content %}
    <div>
        <div>
            <form action="{{ post.get_delete_url }}" method="post">
            {% csrf_token %}
                <p>Are you sure that you want to delete post {{ post.title }}?</p>
                <a href="{{ post.get_absolute_url }}">Cancel</a>
                <button type="submit">Delete</button>
            </form>
        </div>
    </div>
{% endblock %}

suorganizer/blog/templates/blog/post_detail.html
{% extends parent_template|default:"blog/base_blog.html" %}
{% block title %}
    {{ block.super }} - {{ post.title|title }}
{% endblock %}

{% block content %}
<article>
    <header>
        <h2>
           {{ post.title|title }}
        </h2>
        <p>Written on <time datetime="{{ post.pub_date|date:"Y-m_d" }}">
            {{ post.pub_date|date:"l, F j, Y" }}
        </time></p>
    </header>

    {{ post.text|linebreaks }}

    {% if post.startups.all or post.tags.all %}
        <footer>
        {% if post.startups.all %}
            <section>
                <h3>Startup{{ post.startups.count|pluralize }}</h3>
                <ul>
                    {% for startup in post.startups.all %}
                        <li>
                            <a href="{{ startup.get_absolute_url }}">
                                {{ startup.name }}
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            </section>
        {% endif %}
        {% if post.tags.all %}
            <section>
                <h3>Tag{{ post.tags.count|pluralize }}</h3>
                <ul>
                    {% for tag in post.tags.all %}
                        <li>
                            <a href="{{ tag.get_absolute_url }}">
                                {{ tag.name|title }}
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            </section>
        {% endif %}
        </footer>
    {% endif %}
</article>
{% endblock %}

suorganizer/blog/templates/blog/post_form.html
{% extends parent_template|default:"blog/base_blog.html" %}

{% block title %}
    {{ block.super }}- Create Blog Post
{% endblock %}

{% block content %}
    <div>
        <div>
        <form action="{% url 'blog_post_create' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create Blog Post</button>
        </form>
        </div>
    </div>
{% endblock %}

suorganizer/blog/templates/blog/post_form_update.html
{% extends parent_template|default:"blog/base_blog.html" %}

{% block title %}
    {{ block.super }}- Update Blog Post
{% endblock %}

{% block content %}
    <div>
        <div>
        <form action="{{ post.get_update_url }}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Post Form Update</button>
        </form>
        </div>
    </div>
{% endblock %}

suorganizer/blog/templates/blog/post_list.html
{% extends parent_template|default:"blog/base_blog.html" %}
{% block title %}
    {{ block.super }} - {{ post.title|title }}
{% endblock %}

{% block content %}
{% for post in post_list %}
    <article>
        <header>
            <h2>
                <a href="{{ post.get_absolute_url }}">
                    {{ post.title|title }}
                </a>
            </h2>
            <p>
                Written on :
                <time datetime="{{ post.pub_date|date:"Y-m_d" }}">
                {{ post.pub_date|date:"l,F j, Y" }}
                </time>
            </p>
        </header>
        <p>{{ post.text|truncatewords:20 }}</p>
        <p>
            <a href="{{ post.get_absolute_url }}">
            Read more&hellip;
            </a>
        </p>
    </article>
{% empty %}
    <p><em>No Blog Posts Available</em></p>
{% endfor %}
{% endblock %}

suorganizer/organizer/templates/organizer/base_organizer.html
{% extends parent_template|default:"base.html" %}

suorganizer/organizer/templates/organizer/newslink_confirm_delete.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
    {{ block.super }} - Delete Newslink
{% endblock %}

{% block content %}
    <div>
        <div>
            <form action="{{ newslink.get_delete_url }}" method="post">
            {% csrf_token %}
                <p>Are you sure that you want to delete newslink {{ newslink.title }}?</p>
                <a href="{{ newslink.get_absolute_url }}">Cancel</a>
                <button type="submit">Delete</button>
            </form>
        </div>
    </div>
{% endblock %}

suorganizer/organizer/templates/organizer/newslink_form.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
    {{ block.super }}- Link News Article to Startup
{% endblock %}

{% block content %}
    <div>
        <div>
        <form action="{% url 'organizer_newslink_create' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Link Article</button>
        </form>
        </div>
    </div>
{% endblock %}

suorganizer/organizer/templates/organizer/newslink_form_update.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
    {{ block.super }} - Update Newslink
{% endblock %}

{% block content %}
    <div>
        <div>
            <form action="{{ newslink.get_update_url }}" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Update Newslink</button>
            </form>
        </div>
    </div>
{% endblock %}

suorganizer/organizer/templates/organizer/startup_confirm_delete.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
    {{ block.super }} - Delete Startup
{% endblock %}

{% block content %}
    <div>
        <div>
            <form action="{{ startup.get_delete_url }}" method="post">
            {% csrf_token %}
                <p>Are you sure that you want to delete startup {{ startup.name }}?</p>
                <a href="{{ startup.get_absolute_url }}">Cancel</a>
                <button type="submit">Delete</button>
            </form>
        </div>
    </div>
{% endblock %}

suorganizer/organizer/templates/organizer/startup_detail.html
{% extends parent_template|default:"organizer/base_organizer.html" %}
{% block title %}
    Startup Detail
{% endblock %}

{% block content %}
<article>

    <h2>
        {{ startup.name }}
    </h2>
    <dl>
        <dt>Date Founded</dt>
        <dd>{{ startup.founded_date|date:"F jS, Y" }}</dd>
        <dt>Website</dt>
        <dd>{{ startup.website|urlize }}</dd>
        <dt>Contact</dt>
        <dd>{{ startup.contact }}</dd>

        <dt>Tag{{ startup.tags.count|pluralize }}</dt>
        {% for tag in startup.tags.all %}
            <dd>
            <a href="{{ tag.get_absolute_url }}">
                {{ tag.name|title }}
            </a>
            </dd>
        {% endfor %}
    </dl>

    {{ startup.description|linebreaks }}

    {% if startup.newslink_set.all %}
        <section>
            <h3>Recent News</h3>
            <ul>
                {% for newslink in startup.newslink_set.all %}
                    <li>
                    <a href="{{ newslink.link }}">
                        {{ newslink.title|title }}
                    </a>
                    </li>
                {% endfor %}
            </ul>
        </section>
    {% endif %}

    {% if startup.blog_posts.all %}
        <section>
            <h3>Blog Post{{ startup.blog_posts.count|pluralize }}</h3>
            <ul>
            {% for post in startup.blog_posts.all %}
                <li>
                    <a href="{{ post.get_absolute_url }}">
                        {{ post.title|title }}
                    </a>
                </li>
            {% endfor %}
            </ul>
        </section>
    {% endif %}

</article>
{% endblock %}

suorganizer/organizer/templates/organizer/startup_form.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - Create Startup
{% endblock %}

{% block content %}
    <div>
        <div>
            <form action="{% url 'organizer_startup_create' %}" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Create Startup</button>
            </form>
        </div>
    </div>
{% endblock %}

suorganizer/organizer/templates/organizer/startup_form_update.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - Update Startup
{% endblock %}

{% block content %}
    <div>
        <div>
            <form action="{{ startup.get_update_url }}" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Update Startup</button>
            </form>
        </div>
    </div>
{% endblock %}

suorganizer/organizer/templates/organizer/startup_list.html
{% extends parent_template|default:"organizer/base_organizer.html" %}
{% block title %}{{ block.super }} - Startup List{% endblock %}

{% block content %}
<h2>Startup List</h2>
<ul>
    {% for startup in startup_list %}
        <li>
            <a href="{{ startup.get_absolute_url }}">
                {{ startup.name }}
            </a>
        </li>
    {% empty %}
        <li><em>No Startup Available.</em></li>
    {% endfor %}
</ul>
{% endblock %}

suorganizer/organizer/templates/organizer/tag_confirm_delete.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
    {{ block.super }} - Delete Tag
{% endblock %}

{% block content %}
    <div>
        <div>
            <form action="{{ tag.get_delete_url }}" method="post">
            {% csrf_token %}
                <p>Are you sure that you want to delete tag {{ tag.name }}?</p>
                <a href="{{ tag.get_absolute_url }}">Cancel</a>
                <button type="submit">Delete</button>
            </form>
        </div>
    </div>
{% endblock %}

suorganizer/organizer/templates/organizer/tag_detail.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - {{ tag.name|title }}
{% endblock %}

{% block content %}
<h2>{{ tag.name|title }}</h2>
{% if tag.startup_set.all %}
<section>
    <h3>Startup{{ tag.startup_set.count|pluralize }}</h3>
    <p>
        Tag is associated with
        {{ tag.startup_set.count }}
        startup{{ tag.startup_set.count|pluralize }}.
    </p>
    <ul>
        {% for startup in tag.startup_set.all %}
        <!-- list of startups related to tags -->
        <li>
            <a href="{{ startup.get_absolute_url }}">
                {{ startup.name }}
            </a>
        </li>
        {% endfor %}
    </ul>
</section>
{% endif %}
{% if tag.blog_posts.all %}
<section>
    <h3>Blog Post{{ tag.blog_posts.count|pluralize }}</h3>
    <ul>
        {% for post in tag.blog_posts.all %}
        <!-- list of posts related to tag -->
            <li>
                <a href="{{ post.get_absolute_url }}">
                    {{ post.title|title }}
                </a>
            </li>
        {% endfor %}
    </ul>
</section>
{% endif %}
{% if not tag.startup_set.all and not tag.blog_posts.all %}
    <p>This is not related to any content.</p>
{% endif %}
{% endblock %}

suorganizer/organizer/templates/organizer/tag_form.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
    {{ block.super }}- Create Tag
{% endblock %}

{% block content %}
    <div>
        <div>
        <form action="{% url 'organizer_tag_create' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create Tag</button>
        </form>
        </div>
    </div>
{% endblock %}

suorganizer/organizer/templates/organizer/tag_form_update.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
    {{ block.super }} - Update Tag
{% endblock %}

{% block content %}
    <div>
        <div>
            <form action="{{ tag.get_update_url }}" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Update Tag</button>
            </form>
        </div>
    </div>
{% endblock %}

suorganizer/organizer/templates/organizer/tag_list.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - Tag List
{% endblock %}

{% block content %}
<h2>Tag List</h2>
<ul>
    {% for tag in tag_list %}
    <li>
        <a href="{{ tag.get_absolute_url }}">
            {{ tag.name|title }}
        </a>
    </li>
    {% empty %}
    <li><em>There are currently no tags available</em></li>
    {% endfor %}
</ul>
{% endblock %}

suorganizer/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>
        {% block title %}Startup Organizer{% endblock %}
    </title>

</head>
<body>
    <!--container-->
<div>
    <header>
        <h1>Startup Organizer</h1>
    </header>
    <main>
        {% block content %}
        This is default content!
        {% endblock %}
    </main>
</div>
    <!--container-->
<nav>
    <ul>
        <li>
            <a href="{% url 'blog_post_list' %}">
                Blog
            </a>
        </li>
        <li>
            <a href="{% url 'organizer_startup_list' %}">
                Startup
            </a>
        </li>
        <li>
            <a href="{% url 'organizer_tag_list' %}">
                Tags
            </a>
        </li>
    </ul>
</nav>

<footer>
    <p>
        &copy;2017
        <a href="https://AndrewsForge.com/">
            Andrew Pinkham
        </a>
    </p>
    <p>
        Created for
        <a href="https://Django-Unleashed.com/">
            Django Unleashed
        </a>
    </p>
</footer>
</body>
</html>